import * as api from './server'
import serverConfig from './commonConfig'
export const base = serverConfig.base
    // 每一个项目必定存在
export const getApp = params => api.get(`${base}/app/findById`, params)
export const getSessionId = params => api.get(`${base}/account/sessionId`, params)
export const send_code = params => api.get(`${base}send_code`, params)
export const admin_register = params => api.post(`${base}admin_register`, params)
export const admin_login = params => api.post(`${base}admin_login`, params)
export const upload = params => api.post(`${base}upload`, params)
export const find_password = params => api.post(`${base}find_password`, params)
export const newCreateShop = params => api.post(`${base}newCreateShop`, params)
export const show_shop = params => api.get(`${base}show_shop`, params)
export const del_shop = params => api.get(`${base}del_shop`, params)
export const update_shop = params => api.post(`${base}update_shop`, params)
export const show_forum = params => api.get(`${base}show_forum`, params)
export const show_info = params => api.get(`${base}show_info`, params)
export const remove_forum = params => api.get(`${base}remove_forum`, params)
export const is_best = params => api.get(`${base}is_best`, params)
export const is_top = params => api.get(`${base}is_top`, params)
export const card_number = params => api.get(`${base}card_number`, params)
export const new_people = params => api.get(`${base}new_people`, params)
export const week_people = params => api.get(`${base}week_people`, params)
export const sumpeople = params => api.get(`${base}sum`, params)
export const show_record = params => api.get(`${base}show_record`, params)
export const search_card = params => api.get(`${base}search_card`, params)
export const shop_desc = params => api.get(`${base}shop_desc`, params)
export const downfile = params => api.get(`${base}downfile`, params)
export const send = params => api.post(`${base}send`, params)
export const admin_wait = params => api.get(`${base}admin_wait`, params)
export const admin_already = params => api.get(`${base}admin_already`, params)
export const admin_finish = params => api.get(`${base}admin_finish`, params)
export const get_refund = params => api.get(`${base}get_refund`, params)
export const get_shipping = params => api.get(`${base}get_shipping`, params)
export const day_order = params => api.get(`${base}day_order`, params)
export const count_order = params => api.get(`${base}count_order`, params)
export const day_money = params => api.get(`${base}day_money`, params)
export const mon_money = params => api.get(`${base}mon_money`, params)
export const money = params => api.get(`${base}money`, params)
export const sel_cate = params => api.get(`${base}sel_cate`, params)
export const del_cate = params => api.get(`${base}del_cate`, params)
export const add_cate = params => api.post(`${base}add_cate`, params)
export const edit_cate = params => api.post(`${base}edit_cate`, params)
export const goods_add = params => api.post(`${base}goods_add`, params)
export const goods_show = params => api.get(`${base}goods_show`, params)
export const goods_del = params => api.get(`${base}goods_del`, params)
export const goods_delete = params => api.get(`${base}goods_delete`, params)
export const goods_edit = params => api.get(`${base}goods_edit`, params)
export const deposit = params => api.post(`${base}deposit`, params)
export const shop_info = params => api.get(`${base}shop_info`, params)
export const solve = params => api.get(`${base}solve`, params)
export const admin_search_goods = params => api.get(`${base}admin_search_goods`, params)
export const order_num = params => api.get(`${base}order_num`, params)
export const remove_card = params => api.get(`${base}remove_card`, params)
export const week_order = params => api.get(`${base}week_order`, params)
export const set_commend = params => api.get(`${base}set_commend`, params)
export const admin_reply = params => api.post(`${base}admin_reply`, params)
export const update_cash = params => api.post(`${base}update_cash`, params)
export const add_cash = params => api.post(`${base}add_cash`, params)
export const cash_list = params => api.get(`${base}cash_list`, params)
export const del_cash = params => api.get(`${base}del_cash`, params)
export const add_spec = params => api.post(`${base}add_spec`, params)
export const add_attr = params => api.post(`${base}add_attr`, params)
export const attr_list = params => api.get(`${base}attr_list`, params)
export const update_attr = params => api.get(`${base}update_attr`, params)
export const del_attr = params => api.get(`${base}del_attr`, params)
export const spec_list = params => api.get(`${base}spec_list`, params)
export const update_spec = params => api.post(`${base}update_spec`, params)
export const del_spec = params => api.get(`${base}del_spec`, params)
export const goods_pro_add = params => api.post(`${base}goods_pro_add`, params)
export const goods_pro_edit = params => api.post(`${base}goods_pro_edit`, params)
export const search_spec = params => api.get(`${base}search_spec`, params)
export const getToken = params => api.get(`${base}getToken`, params)
export const get_shop_user = params => api.get(`${base}get_shop_user`, params)
export const show_no_sale = params => api.get(`${base}show_no_sale`, params)
export const set_on_sale = params => api.get(`${base}set_on_sale`, params)
export const admin_goods_list = params => api.get(`${base}admin_goods_list`, params)
export const join_register = params => api.post(`${base}join_register`, params)
export const join_info = params => api.get(`${base}join_info`, params)
export const adjust_order = params => api.post(`${base}adjust_order`, params)
export const search_goods = params => api.get(`${base}search_goods`, params)
export const show_cut = params => api.get(`${base}show_cut`, params)
export const add_cut = params => api.post(`${base}add_cut`, params)
export const set_cut = params => api.get(`${base}set_cut`, params)
export const admin_waits = params => api.get(`${base}admin_waits`, params)
export const search_attr = params => api.get(`${base}search_attr`, params)
export const get_goods = params => api.get(`${base}get_goods`, params)
export const admin_all_wait = params => api.get(`${base}admin_all_wait`, params)
export const remove_cash = params => api.get(`${base}remove_cash`, params)
export const admin_shop_info = params => api.get(`${base}admin_shop_info`, params)
export const admin_wait_experience = params => api.get(`${base}admin_wait_experience`, params)
export const admin_already_experience = params => api.get(`${base}admin_already_experience`, params)
export const confirm_experience = params => api.post(`${base}confirm_experience`, params)
export const dada_index = params => api.post(`${base}dada_index`, params)
export const get_citycode_list = params => api.get(`${base}get_citycode_list`, params)
export const get_dada_status = params => api.get(`${base}get_dada_status`, params)
export const set_auth = params => api.get(`${base}set_auth`, params)
export const post_set = params => api.post(`${base}post_set`, params)
export const post_get = params => api.get(`${base}post_get`, params)
export const wxpay_set = params => api.post(`${base}wxpay_set`, params)
export const get_category = params => api.get(`${base}get_category`, params)
export const submit_audit = params => api.post(`${base}submit_audit`, params)
export const app_set = params => api.post(`${base}app_set`, params)
export const app_get = params => api.get(`${base}app_get`, params)
export const submit_code = params => api.post(`${base}submit_code`, params)
export const update_access_token = params => api.get(`${base}update_access_token`, params)
export const get_exp_version = params => api.get(`${base}get_exp_version`, params)
export const set_business_domain = params => api.post(`${base}set_business_domain`, params)
export const set_server_domain = params => api.post(`${base}set_server_domain`, params)
export const get_audit_status = params => api.get(`${base}get_audit_status`, params)
export const release = params => api.get(`${base}release`, params)
export const get_app_info = params => api.get(`${base}get_app_info`, params)
export const bind_tester = params => api.get(`${base}bind_tester`, params)
export const get_saleUserAdmin = params => api.get(`${base}get_saleUserAdmin`, params)
export const get_shopConfigDetail = params => api.get(`${base}get_shopConfigDetail`, params)
export const post_shopConfigDetail = params => api.post(`${base}post_shopConfigDetail`, params)
export const get_plat_info = params => api.get(`${base}get_plat_info`, params)
export const get_requestStatus = params => api.post(`${base}get_requestStatus`, params)
export const wxpay_get = params => api.get(`${base}wxpay_get`, params)
export const cashAdminDetail = params => api.get(`${base}cashAdminDetail`, params)
export const upCashStatus = params => api.get(`${base}upCashStatus`, params)
export const goodsGroups = params => api.get(`${base}goodsGroups`, params)
export const upGoodsGroupStatus = params => api.post(`${base}upGoodsGroupStatus`, params)
export const get_money = params => api.get(`${base}get_money`, params)
export const get_order = params => api.get(`${base}get_order`, params)
export const get_province = params => api.get(`${base}get_province`, params)
export const get_city = params => api.get(`${base}get_city`, params)
export const get_county = params => api.get(`${base}get_county`, params)
export const show_admin_shop_info = params => api.get(`${base}show_admin_shop_info`, params)
export const up_shopInfo = params => api.post(`${base}up_shopInfo`, params)
export const get_dispatch = params => api.get(`${base}get_dispatch`, params)
export const up_dispatch = params => api.post(`${base}up_dispatch`, params)
export const get_showArea = params => api.get(`${base}get_showArea`, params)
export const add_expressFee = params => api.post(`${base}add_expressFee`, params)
export const del_express = params => api.get(`${base}del_express`, params)
export const addCity = params => api.get(`${base}addCity`, params)
export const add_dada_shop = params => api.post(`${base}add_dada_shop`, params)
export const get_shop_dada_config = params => api.get(`${base}get_shop_dada_config`, params)
export const edit_data_shop = params => api.post(`${base}edit_data_shop`, params)
export const recharge = params => api.post(`${base}recharge`, params)
export const access_print = params => api.post(`${base}access_print`, params)
export const select_one = params => api.get(`${base}select_one`, params)
export const get_print_config = params => api.get(`${base}get_print_config`, params)
export const deskQrcode = params => api.get(`${base}deskQrcode`, params)
export const get_groupApplyAdmin = params => api.get(`${base}get_groupApplyAdmin`, params)
export const up_groupApplyAdmin = params => api.post(`${base}up_groupApplyAdmin`, params)
export const getGroupQRcode = params => api.get(`${base}getGroupQRcode`, params)
export const groupCashAdminDetail = params => api.get(`${base}groupCashAdminDetail`, params)
export const up_groupCashStatus = params => api.get(`${base}up_groupCashStatus`, params)
export const downloadGroupQRcode = params => api.get(`${base}downloadGroupQRcode`, params)
export const cash_group_detail = params => api.get(`${base}cash_group_detail`, params)
export const waitGroupAdmin = params => api.get(`${base}waitGroupAdmin`, params)
export const alreadlyGroupAdmin = params => api.get(`${base}alreadlyGroupAdmin`, params)
export const reduseGroupAdmin = params => api.get(`${base}reduseGroupAdmin`, params)
export const waitAdminGroup = params => api.get(`${base}waitAdminGroup`, params)
export const newWaitGroupOrder = params => api.get(`${base}newWaitGroupOrder`, params)
export const deliver = params => api.get(`${base}deliver`, params)
export const printGroupSignture = params => api.post(`${base}printGroupSignture`, params)
export const bulkPrint = params => api.post(`${base}bulkPrint`, params)
export const fictitiousGroup = params => api.get(`${base}fictitiousGroup`, params)
export const addFictitiousGroupUser = params => api.get(`${base}addFictitiousGroupUser`, params)
export const getGroupAll = params => api.get(`${base}getGroupAll`, params)
export const getGroupSort = params => api.get(`${base}getGroupSort`, params)
export const upGroupSort = params => api.post(`${base}upGroupSort`, params)
export const newWaitRefuseGroupOrder = params => api.get(`${base}newWaitRefuseGroupOrder`, params)
export const addGroupFriends = params => api.post(`${base}addGroupFriends`, params)
export const delGroupFriends = params => api.get(`${base}delGroupFriends`, params)
export const getGroupFriends = params => api.get(`${base}getGroupFriends`, params)
export const wxGroupFriend = params => api.get(`${base}wxGroupFriend`, params)
export const totalOrderCount = params => api.get(`${base}totalOrderCount`, params)
export const getGroupUserDetail = params => api.get(`${base}getGroupUserDetail`, params)
export const printUserAll = params => api.get(`${base}printUserAll`, params)
export const NewSend = params => api.get(`${base}NewSend`, params)
export const newWaitOrderAddress = params => api.get(`${base}newWaitOrderAddress`, params)
export const getUserInfo  = params => api.get(`${base}getUserInfo`, params)
export const addUserInfo  = params => api.post(`${base}addUserInfo `, params)
export const getUserDistriBution  = params => api.get(`${base}getUserDistriBution`, params)
export const newWaitOrder = params => api.get(`${base}newWaitOrder`,params)
export const getDistriBution = params => api.get(`${base}getDistriBution`,params)
export const delUserInfo = params => api.get(`${base}delUserInfo`,params)
export const getFriendIncome = params => api.get(`${base}getFriendIncome`,params)
export const friendCash  = params => api.post(`${base}friendCash `, params)
export const upFriendStatus  = params => api.post(`${base}upFriendStatus `, params)
export const getFriendDetail = params => api.get(`${base}getFriendDetail`,params)
export const sel_cate_shop = params => api.get(`${base}sel_cate_shop`,params)
export const sel_cate_all = params => api.get(`${base}sel_cate_all`,params)
export const deleteShop = params => api.get(`${base}deleteShop`,params)
export const pay_status = params => api.get(`${base}pay_status`,params)
export const onsale_status = params => api.get(`${base}onsale_status`,params)
export const time_trade = params => api.get(`${base}time_trade`,params)
export const updateSellerRadio = params => api.post(`${base}updateSellerRadio`,params)
